db:
  host: "localhost"
  port: 3306
  database: "testdb"
  username: "root"
  password: "example"
  synchronize: true

jwt:
  secret: "topSecret51"

redis:
  host: "localhost"
  port: 6379
  # password: "random-pass"
