db:
  host: "hw.prod.toimc.com"
  port: 11000
  database: "toimcdb"
  username: "toimc"
  password: "Ok8sJ7xMsoj63i38dD"
  synchronize: true

jwt:
  secret: "topSecret51"

redis:
  host: "hw.prod.toimc.com"
  port: 43006
  password: "n85Arxyl75Uiwv1jXmiL5opOmgvznJX9"
